# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_aquarium_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquarium',
            name='SpisokRyb',
            field=models.ManyToManyField(to='app1.Fish'),
        ),
    ]
