# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_aquarium_spisokryb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='AquariumList',
        ),
        migrations.RemoveField(
            model_name='user',
            name='SpisokTipovRyb',
        ),
        migrations.RenameField(
            model_name='aquarium',
            old_name='aquariumVolume',
            new_name='FilledVolume',
        ),
        migrations.RenameField(
            model_name='aquarium',
            old_name='totalVolume',
            new_name='Volume',
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='fishType',
            new_name='FishType',
        ),
        migrations.RemoveField(
            model_name='aquarium',
            name='SpisokRyb',
        ),
        migrations.AddField(
            model_name='aquarium',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fish',
            name='Aquarium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Aquarium'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fishtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
