# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20160424_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquarium',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
