# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_fish_fishtypeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='FishTypeID',
        ),
    ]
