# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_fish_fishtypeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='FishType',
            new_name='FishTypeKey',
        ),
    ]
