# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20160515_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='Name',
            field=models.CharField(default='Fish', max_length=30),
        ),
    ]
